# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         DTP
version:      0.0.1
version_from: lib/DTP.pm
installdirs:  site
requires:
    Data::Dumper:                  0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
